[iOS] Support RTL
RedMadRobot/figma-export pull request #180
Opened 2022-07-12 06:38 UTC by alexey1312

From discussions https://github.com/RedMadRobot/figma-export/discussions/133

2022-07-13 19:22 UTC, subdan requested changes
Add info about supporting RTL to the README.md.

2022-07-13 19:22 UTC, subdan commented on Sources/FigmaExport/Loaders/ImagesLoader.swift
> +        return false
Use `localizedCaseInsensitiveContains` method to perform case-insensitive search.

```suggestion
        return description.localizedCaseInsensitiveContains("rtl")
```

2022-07-13 19:23 UTC, subdan commented
Hi, @alexey1312. Thanks for the PR! Will you use this feature in your project?

2022-07-14 03:59 UTC, alexey1312 commented
> Hi, @alexey1312. Thanks for the PR! Will you use this feature in your project?

Hi! Yes, we will 🚀
We know about the [problem](https://useyourloaf.com/blog/flipping-and-localizing-image-assets/), but I tested the solution above, it works well.

Maybe in the future, it's worth adding Stencil Templates, with .flipsForRightToLeftLayoutDirection(true) for icons.

2022-07-14 16:13 UTC, subdan commented on README.md
> +If a icon is support RTL (iOS only), it should contains "rtl" word in the description field in the properties.
```suggestion
If an icon supports RTL (iOS only), it should contains "rtl" word in the description field in the properties.

2022-07-14 19:11 UTC, merged