Add support for exporting colors from variables
RedMadRobot/figma-export pull request #236
Opened 2024-04-03 14:20 UTC by alexey1312

- Added`ColorsVariablesLoader`
- Updated doc

From the documentation:

<img src=https://github.com/RedMadRobot/figma-export/assets/36570774/84a23041-8b16-45b7-b67e-626a4dbe0b4d width="800"/>

1. tokensCollectionName - the name of the variable collection
2. lightModeName - the name of the color variable column for the light theme
3. darkModeName - the name of the color variable column for the dark theme
4. lightHCModeName - the name of the color variable column for the light theme with high contrast
5. darkHCModeName - the name of the color variable column for the dark theme with high contrast
6. A variable that has a local value
7. A variable that refers to another variable in a different file

<img src=https://github.com/RedMadRobot/figma-export/assets/36570774/c5350259-fae6-4776-82f7-abe72b78f012 height="300"/>

1. primitivesModeName - the name of the variable column, if the value in [CONFIG.md](CONFIG.md) is not specified, the default value will be used
2. A variable that has a local value

fyi:
https://github.com/RedMadRobot/figma-export/issues/217

2024-04-07 17:16 UTC, subdan requested changes

2024-04-08 03:36 UTC, alexey1312 commented on README.md
> +**Important, in [CONFIG.md](CONFIG.md) use either colors or variablesColors.**
done ✅

2024-04-08 03:36 UTC, alexey1312 commented on README.md
> +With the introduction of color variables in Figma, you can use color variables instead of color styles. Color variables can be used in figma-export, for this in [CONFIG.md](CONFIG.md) you need to use
done ✅

2024-04-08 03:36 UTC, alexey1312 commented on README.md
> +See [CONFIG.md](CONFIG.md) for more information in the variablesColors section.
done ✅

2024-04-08 03:36 UTC, alexey1312 commented on README.md
> +1. primitivesModeName - the name of the variable column, if the value in [CONFIG.md](CONFIG.md) is not specified, the default value will be used
done ✅

2024-04-08 03:36 UTC, alexey1312 commented on Sources/FigmaExport/Subcommands/ExportColors.swift
> +                nameReplaceRegexp = options.params.common?.variablesColors?.nameReplaceRegexp
done ✅

2024-04-08 03:36 UTC, alexey1312 commented on Sources/FigmaExport/Subcommands/ExportColors.swift
> +                loader = ColorsLoader(
done ✅

2024-04-08 03:36 UTC, alexey1312 commented on Sources/FigmaAPI/Model/Variables.swift
> +    public var variables: [String: VariableID]
done ✅

2024-04-08 03:36 UTC, alexey1312 commented on Sources/FigmaAPI/Model/Variables.swift
> +            self = .boolean(boolean)
done ✅

2024-04-08 03:36 UTC, alexey1312 commented on Sources/FigmaAPI/Model/Variables.swift
> +    public var hiddenFromPublishing: Bool
done ✅

2024-04-08 03:37 UTC, alexey1312 commented on Sources/FigmaAPI/Model/Variables.swift
> +public struct VariableCollectionId: Decodable {
done ✅

2024-04-08 03:37 UTC, alexey1312 commented on Sources/FigmaExport/Subcommands/ExportColors.swift
> +                nameReplaceRegexp = options.params.common?.colors?.nameReplaceRegexp
done ✅

2024-04-08 17:17 UTC, merged