Make file download requests chunked
RedMadRobot/figma-export pull request #75
Opened 2021-02-19 12:00 UTC by NoFearJoe

I've found an issue with fetching asset files – if there are many files in a frame, you get the `Request timed out` error after 60 seconds of downloading.

This happens because all file download requests add in a URLSession at the same moment. URLSession has a maximum simultaneous requests count and all requests after this count wait in the queue. And when this is their turn to execute, they have already timed out.

I solved this problem by chunking requests in `FileDownloader`.

2021-02-19 12:54 UTC, subdan commented on Sources/FigmaExportCore/Extensions/Array+chunked.swift
> +//  File.swift
Fix file header

2021-02-19 12:54 UTC, subdan commented on Sources/FigmaExportCore/Extensions/Array+chunked.swift
> +//  File.swift
FigmaExport do not use file headers

2021-02-19 12:56 UTC, NoFearJoe commented on Sources/FigmaExportCore/Extensions/Array+chunked.swift
> +//  File.swift
Done

2021-02-19 12:57 UTC, subdan commented on Sources/FigmaExport/Output/FileDownloader.swift
> +        let chankedFiles = files.chunked(
Fix typo. chunkedFiles

2021-02-19 13:02 UTC, NoFearJoe commented on Sources/FigmaExport/Output/FileDownloader.swift
> +        let chankedFiles = files.chunked(
Done

2021-02-19 15:06 UTC, Alexander-Ignition commented
Привет, @NoFearJoe 

У тебя получилось интересное решение через `DispatchGroup`.  
На каком примерно количестве запросов и объеме ресурсов у тебя получилось оптимизировать загрузку?

Жаль что у нас нет тестов на это. 
Не хочешь ли еще ускорить загрузку используя `DispatchSemaphore` вместо чанков с `DispatchGroup`?

2021-02-19 17:54 UTC, NoFearJoe commented
@Alexander-Ignition , привет.

У нас сейчас чуть больше ста иллюстраций во фрейме. Учспевали скачаться примерно половина из них.

Я думал сначала сделать на `DispatchSemaphore`, но решил не отходить далеко от вашего подхода. Могу переделать и добавить тестов.

2021-02-20 10:18 UTC, subdan commented
> Я думал сначала сделать на `DispatchSemaphore`, но решил не отходить далеко от вашего подхода. Могу переделать и добавить тестов.

Да, надо переделать на `DispatchSemaphore `. Это в несколько раз ускорит скачивание файлов.

С `DispatchSemaphore` 120 больших картинок скачиваются за 9 сек.

<img width="1089" alt="semaphore_9sec" src="https://user-images.githubusercontent.com/410293/108592164-97cf8d00-737d-11eb-9776-63697cd7f87f.png">

Вот код этого решения — https://gist.github.com/subdan/76316cfb2a9144249c5a512c27e56b63 Можешь отсюда скопировать, только os_signpost удали.


Твое решение с разбиением на группы отрабатывает за 30 сек с теми же 120 картинками.

<img width="1207" alt="no_semaphore_30sec" src="https://user-images.githubusercontent.com/410293/108592163-969e6000-737d-11eb-83d9-e8a5e22a1a40.png">

2021-02-20 10:28 UTC, subdan commented
Для сравнения, вот как скачиваются файлы сейчас в master.

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/410293/108592422-e4679800-737e-11eb-9592-f94b3f49916d.png">

Видно, что общее время загрузки файлов почти не отличается от моего решения с `DispatchSemaphore`. Но тут важно, что задача на загрузку файла может очень долго ждать своей очереди из-за чего может возникнуть таймаут.  Надеюсь решение с `DispatchSemaphore` поможет вам избавится от проблемы с тайм-аутом.

2021-02-27 06:33 UTC, NoFearJoe commented
@subdan Использовал твой код с семафором. Спасибо)

2021-03-01 18:43 UTC, subdan commented on Sources/FigmaExport/Output/FileDownloader.swift
> +        let semaphore = DispatchSemaphore(value: session.configuration.httpMaximumConnectionsPerHost)
Тут должно быть `session.configuration.httpMaximumConnectionsPerHost - 1` так как поток блокируется при отрицательном значении счетчика. Если оставить как есть то вместо 6 параллельных запросов будет отправляться 7.

2021-03-01 19:03 UTC, subdan requested changes
Поправь начальное значение у DispatchSemaphore

2021-03-02 08:28 UTC, NoFearJoe commented
Поправил

2021-03-02 09:23 UTC, subdan approved these changes

2021-03-02 09:26 UTC, merged

2021-03-02 09:40 UTC, subdan commented
Опубликовал новую версию. Проверь, работает ли теперь экспорт картинок.

2021-03-04 07:40 UTC, NoFearJoe commented
@subdan Заработало