Add option for android color hex format
RedMadRobot/figma-export pull request #80
Opened 2021-02-26 08:05 UTC by lichin-lin

## Description

As mentioned in #79 , there should provide a way for user to choose either export colors in `rgba` or `arbg` format.

## Changes
* Added params to the yaml file: `hexFormat`
* Change private extension Color's hex (in AndroidColorExporter.swift) from variable to a function.

Fixes #79

2021-02-26 13:16 UTC, subdan requested changes
Hello. Thanks for the PR. I know that colors in android always specified in ARGB format. It is an FigmaExport error to export colors for android in RGBA format. So, we don’t need a new parameter (android.color.hexFormat). Just change RGBA to ARGB format in the `AndroidColorExporter.swift`.

2021-02-28 23:41 UTC, lichin-lin commented
Ok 🙂 thanks for the explanation! let me do a update tomorrow and send the PR again.

2021-03-02 02:51 UTC, lichin-lin commented
@subdan I've update the code, please review when have time, thanks 😀

2021-03-02 06:07 UTC, subdan commented on README.md
> +Colors will be exported to `values/colors.xml` and `values-night/colors.xml` files in `argb` format.
It is a default format. Discard this change.

2021-03-02 06:08 UTC, subdan requested changes
Discard changes to the README.md.

2021-03-02 06:53 UTC, subdan approved these changes

2021-03-02 06:55 UTC, merged